import { GameDetails } from './gameDetails';
import { userData } from "./userData";


export const UsersData: userData[] = [
    {
        id: 1,
        username: "aayush",
        gameDetails: GameDetails,
        orderRoad: [100],
        orderRail: [200],
        inventoryItems: [300,200],
        inventoryCost: [400],
        backlogItems: [400],
        backlogCost: [400],
        demumurageItems: [400],
        demmurageCosts: [400],
        transportationCosts: [400],
        totalCosts: [400],
        totalCost: 300,
        professor:''
    },
    {
        id: 2,
        username: "aayush",
        gameDetails: GameDetails,
        orderRoad: [100],
        orderRail: [200],
        inventoryItems: [300],
        inventoryCost: [400],
        backlogItems: [400],
        backlogCost: [400],
        demumurageItems: [400],
        demmurageCosts: [400],
        transportationCosts: [400],
        totalCosts: [400],
        totalCost: 300,
        professor:''
    },
    {
        id: 3,
        username: "aayush",
        gameDetails: GameDetails,
        orderRoad: [100],
        orderRail: [200],
        inventoryItems: [300],
        inventoryCost: [400],
        backlogItems: [400],
        backlogCost: [400],
        demumurageItems: [400],
        demmurageCosts: [400],
        transportationCosts: [400],
        totalCosts: [400],
        totalCost: 300,
        professor:''
    },
    {
        id: 4,
        username: "aayush",
        gameDetails: GameDetails,
        orderRoad: [100],
        orderRail: [200],
        inventoryItems: [300],
        inventoryCost: [400],
        backlogItems: [400],
        backlogCost: [400],
        demumurageItems: [400],
        demmurageCosts: [400],
        transportationCosts: [400],
        totalCosts: [400],
        totalCost: 300,
        professor:''
    },
    {
        id: 1,
        username: "aayush0019",
        gameDetails: GameDetails,
        orderRoad: [100],
        orderRail: [200],
        inventoryItems: [300],
        inventoryCost: [400],
        backlogItems: [400],
        backlogCost: [400],
        demumurageItems: [400],
        demmurageCosts: [400],
        transportationCosts: [400],
        totalCosts: [400],
        totalCost: 300,
        professor:''
    },
    {
        id: 2,
        username: "aayush0019",
        gameDetails: GameDetails,
        orderRoad: [100],
        orderRail: [200],
        inventoryItems: [300],
        inventoryCost: [400],
        backlogItems: [400],
        backlogCost: [400],
        demumurageItems: [400],
        demmurageCosts: [400],
        transportationCosts: [400],
        totalCosts: [400],
        totalCost: 300,
        professor:''
    },
    {
        id: 3,
        username: "aayush0019",
        gameDetails: GameDetails,
        orderRoad: [100],
        orderRail: [200],
        inventoryItems: [300],
        inventoryCost: [400],
        backlogItems: [400],
        backlogCost: [400],
        demumurageItems: [400],
        demmurageCosts: [400],
        transportationCosts: [400],
        totalCosts: [400],
        totalCost: 300,
        professor:''
    },
    
]